"""GarminPort — domain-owned interface for fetching wearable data.

Day 1 returns raw dicts. When the domain grows (training load calculations,
multi-source aggregation), we'll promote these to typed DTOs/entities and
the port signature evolves with the domain, not the adapter.
"""
from __future__ import annotations

from datetime import date
from typing import Any, Protocol


class GarminPort(Protocol):
    async def get_daily_summary(self, target_date: date) -> dict[str, Any]: ...
    async def get_sleep(self, target_date: date) -> dict[str, Any]: ...
    async def list_activities(self, start: date, limit: int) -> list[dict[str, Any]]: ...
    async def get_activity_details(self, activity_id: str) -> dict[str, Any]: ...
    async def get_hrv(self, target_date: date) -> dict[str, Any]: ...
    async def get_training_readiness(self, target_date: date) -> list[dict[str, Any]]: ...
    async def get_training_status(self, target_date: date) -> dict[str, Any]: ...
    async def get_body_battery(self, start: date, end: date) -> list[dict[str, Any]]: ...
    async def get_stress(self, target_date: date) -> dict[str, Any]: ...
    async def get_user_profile(self) -> dict[str, Any]: ...
    async def get_morning_readiness(self, target_date: date) -> dict[str, Any]: ...
    async def get_personal_records(self) -> list[dict[str, Any]]: ...
